blank_issues_enabled: false
contact_links:
  - name: Vampirism Discord
    url: https://discord.gg/wuamm4P
    about: If you are not sure about something, ask on Discord
  - name: Vampirism Repository
    url: https://github.com/TeamLapen/Vampirism
    about: Request changes to Vampirism itself