modLoader = "javafml"
loaderVersion = "[42,)"
license = "MIT"

[[mods]]
modId = "godly_vampirism"
namespace = "godlyvampirism"
version = "${version}"
displayName = "Godly Vampirism"
authors = "Maxanier"
description = "Remove limitations from Vampirism"
[[dependencies.godly_vampirism]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.godly_vampirism]]
        modId="vampirism"
        mandatory=true
        versionRange="[${vampirism_version},)"
        ordering="AFTER"
        side="BOTH"
